//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pulse8TestConsoleApp.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class Pulse8TestDBEntities : DbContext
    {
        public Pulse8TestDBEntities()
            : base("name=Pulse8TestDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Diagnosi> Diagnosis { get; set; }
        public virtual DbSet<DiagnosisCategory> DiagnosisCategories { get; set; }
        public virtual DbSet<Member> Members { get; set; }
        public virtual DbSet<DiagnosisCategoryMap> DiagnosisCategoryMaps { get; set; }
        public virtual DbSet<MemberDiagnosi> MemberDiagnosis { get; set; }
    
        public virtual ObjectResult<SelectMemberCategories_Result> SelectMemberCategories(Nullable<int> memberID)
        {
            var memberIDParameter = memberID.HasValue ?
                new ObjectParameter("MemberID", memberID) :
                new ObjectParameter("MemberID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SelectMemberCategories_Result>("SelectMemberCategories", memberIDParameter);
        }
    }
}
